CREATE TABLE IF NOT EXISTS product(
id SERIAL PRIMARY KEY,
title VARCHAR(100) NOT NULL,
description VARCHAR(1000),
image VARCHAR(500),
price INTEGER NOT NULL,
stock INTEGER NOT NULL,
created_on TIMESTAMP  WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin(
id SERIAL PRIMARY KEY,
username VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
created_on TIMESTAMP  WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO admin(username, password) VALUES('admin', 'admin12');

CREATE TABLE IF NOT EXISTS phone(
id SERIAL PRIMARY KEY,
number INTEGER NOT NULL,
created_on TIMESTAMP  WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO phone (number) VALUES ('72987877');
